version: "3"

services:
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    image: app:django
    container_name: crudapp_container

    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=restfulapiDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=27032001
    container_name: postgres_db
